all: ML_Colline.cpp ML_Colline.h ML_Desert.cpp ML_Desert.h ML_Foret.cpp ML_Foret.h ML_Mer.cpp ML_Mer.h ML_Montagne.cpp ML_Montagne.h ML_Paturage.cpp ML_Paturage.h ML_Port.cpp ML_Port.h ML_TCultivable.cpp ML_TCultivable.h ML_Terrain.cpp ML_Terrain.h
	g++ -c -g -Wall ML_Colline.cpp ML_Desert.cpp ML_Foret.cpp ML_Mer.cpp ML_Montagne.cpp ML_Paturage.cpp ML_Port.cpp ML_TCultivable.cpp ML_Terrain.cpp
clean:
	rm *.o
