all: ML_Chevalier.cpp ML_Dev.cpp ML_Chevalier.h ML_Dev.h ML_PVictoire.cpp ML_Progres1.cpp ML_Progres2.cpp ML_Progres3.cpp ML_PVictoire.h ML_Progres1.h ML_Progres2.h ML_Progres3.h
	g++ -c -g -Wall ML_Chevalier.cpp ML_Dev.cpp ML_PVictoire.cpp ML_Progres1.cpp ML_Progres2.cpp ML_Progres3.cpp
clean:
	rm *.o
